#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for rewrite
#
# IDENTIFICATION
#    src/backend/rewrite/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/smooth
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = json_builder.o msgq_client.o joincache.o resultcache.o smoothscanopaque.o 

include $(top_srcdir)/src/backend/common.mk

